// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  // Migrations use DIRECT_URL (raw Postgres connection) since DDL through
  // pgbouncer transaction pool can break. Runtime queries (src/lib/db/client.ts)
  // use DATABASE_URL (pooler) for fast warm latency.
  datasource: {
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
